# Generated by Django 3.0.1 on 2019-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slogan', models.SlugField(max_length=100, unique=True)),
                ('position', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
