# Generated by Django 3.0.3 on 2020-02-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191221_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
