# Generated by Django 3.0.3 on 2020-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
