# Generated by Django 3.0.3 on 2020-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200220_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_key',
            field=models.TextField(default=None, null=True),
        ),
    ]
