# Generated by Django 3.0.3 on 2020-02-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200220_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(default=None, null=True, upload_to='images/post'),
        ),
    ]
