# Generated by Django 3.0.3 on 2020-02-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200220_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_key',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
