# Generated by Django 3.0.3 on 2020-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200220_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
