# Generated by Django 3.0.3 on 2020-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200220_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
