# Generated by Django 3.0.3 on 2020-04-04 14:48

from django.db import migrations
from django.db.models import fields


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0017_auto_20200220_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=fields.TextField(),
        ),
    ]
