# Generated by Django 3.0.3 on 2020-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20200404_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slogan',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slogan',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
