# Generated by Django 3.0.3 on 2020-04-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20200413_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
