# Generated by Django 3.0.3 on 2020-04-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20200413_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='views_count',
        ),
    ]
