# Generated by Django 3.0.3 on 2020-04-15 14:55


from django.db import migrations
from django.db.models import fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_auto_20200414_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt_text',
            field=fields.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=fields.TextField(),
        ),
    ]
