# Generated by Django 3.0.3 on 2020-06-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20200425_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-position'], 'verbose_name_plural': 'Санаттар'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Жазбалар'},
        ),
    ]
