# Generated by Django 3.0.3 on 2020-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_auto_20200617_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpPostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('meta_key', models.CharField(default=None, max_length=30)),
                ('meta_value', models.IntegerField()),
            ],
            options={
                'db_table': 'postmeta',
            },
        ),
    ]
