# Generated by Django 3.0.3 on 2020-08-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_auto_20200726_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WpPostMeta',
        ),
    ]
