# Generated by Django 3.0.3 on 2020-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('slug', models.CharField(default=None, max_length=255)),
                ('text', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
    ]
