# Generated by Django 3.0.3 on 2020-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200819_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Жарияланды ма?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default=None, max_length=255, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='views_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Қаралым саны'),
        ),
        migrations.AlterModelTable(
            name='page',
            table='pages',
        ),
    ]
