# Generated by Django 3.0.3 on 2020-08-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0034_delete_wppostmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('url', models.URLField(null=True)),
                ('type', models.CharField(choices=[('category', 'Category'), ('url', 'URL')], default=None, max_length=15)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
            ],
            options={
                'db_table': 'menu_links',
            },
        ),
    ]
