# Generated by Django 3.0.3 on 2020-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('category', 'Санат'), ('url', 'Сілтеме')], default=None, max_length=15),
        ),
    ]
