# Generated by Django 3.0.3 on 2020-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('category', 'Санат'), ('url', 'Сілтеме'), ('page', 'Парақша')], default=None, max_length=15),
        ),
    ]
