# Generated by Django 3.0.3 on 2020-08-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_delete_wppostmeta'),
        ('page', '0002_auto_20200819_2113'),
        ('menu', '0004_auto_20200819_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
