# Generated by Django 3.0.3 on 2020-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200820_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
