# Generated by Django 3.0.3 on 2020-08-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200820_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
