# Generated by Django 3.0.3 on 2020-08-20 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200820_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
