# Generated by Django 3.0.3 on 2020-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('type', models.CharField(choices=[('image', 'Сурет'), ('code', 'Код')], max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('code', models.TextField()),
                ('url', models.URLField()),
                ('position', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
