# Generated by Django 3.0.3 on 2020-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20200821_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='space',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('post_bottom', 'Post bottom')], default='sidebar', max_length=30),
        ),
    ]
